# Generated by Django 2.1.5 on 2019-08-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(blank=True)),
            ],
        ),
    ]
