# Generated by Django 2.1.5 on 2019-08-07 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20190806_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicearea',
            name='fips',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='iso2',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='iso3',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='nation_code',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='pop2005',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='region',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='subregion',
        ),
    ]
